### ISSUE TITLE
Rails 3

### ISSUE THREAD

**Issue by srna** [f0y/redmine_private_wiki#10]
Please update code to support Rails 3.

**Comment by f0y** [comment]
Initial Rails 3 support in branch https://github.com/f0y/redmine_private_wiki/tree/redmine-2.0

**Comment by srna** [comment]
Thanks for your quick reaction, but it did not work for me. However, with my basic skills in RoR, I managed to fix the problem. I don't want to fork for 2 little changes, so I'd suggest these changes:

lib/private_wiki/wiki_page_patch.rb:14 second argument user=User.current (implicitly the current user)
lib/private_wiki/wiki_controller_patch.rb:14 the is_ prefix causes method not found. so it should be !@page.private_page_visible?(...)

Thanks!

**Comment by f0y** [comment]
Yeah, you are right. I was 'writing tests and unfortunately I'd pushed a broken commit. Sorry for this.
New version of plugin will be released soon.
