### ISSUE TITLE
What does private mean?

### ISSUE THREAD

**Issue by cforce** [f0y/redmine_private_wiki#2]
Private ony for the user you created it?
Private for a list of users the creator add to this wiki site by checkbox user-list?
Private for the roles you have read access for private wiki sites? So this would be just another right layer additionally to standard read rights for wiki sites. How does standard wiki rights influence private wiki site right then?
Can u also upload some screeners.
Tx!

**Comment by f0y** [comment]
You are right. This plugin adds his own rights to Redmine roles in addition to standard wiki rights. 
As you see on the screenshot - http://www.redmine.org/attachments/download/7274/private_wiki.png , it adds two fields:
_View_ _private_ _wiki_ _pages_ and _Manage_ _private_ _wiki_ _pages_ to setting.  You can manually mark pages as private and it works like "private issue" functionality which has been added to redmine 1.3.
Firstly, Redmine checks for standard rights. And if a user is allowed to see the page,  the plugin will perform its own checking against user rights and a page type.
