### ISSUE TITLE
Error in redmine 2.3

### ISSUE THREAD

**Issue by majkinetor** [f0y/redmine_private_wiki#20]
<pre>ActionView::Template::Error (undefined method `private' for #<WikiPage:0x000000082c1728>):                                             
    1: <% if controller and controller.class.name == 'WikiController' and controller.action_name == "show" and                         
    2:         @page and @page.id and @page.visible? %>                                                                                
    3:                                                                                                                                 
    4:     <%= link_to_if_authorized(l(:button_hide_wiki), {:action => 'change_privacy', :id => @page.title, :private => 1}, :method =>
 :post, :class => 'icon icon-hide') if !@page.private? %>                                                                              
    5:     <%= link_to_if_authorized(l(:button_reveal_wiki), {:action => 'change_privacy', :id => @page.title, :private => 0}, :method 
=> :post, :class => 'icon icon-reveal') if @page.private? %>                                                                           
  lib/redmine/hook.rb:111:in `block in render_on'                                                                                      
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'                                                                            
  lib/redmine/hook.rb:61:in `each'                                                                                                     
  lib/redmine/hook.rb:61:in `block in call_hook'                                                                                       
  lib/redmine/hook.rb:58:in `tap'                                                                                                      
  lib/redmine/hook.rb:58:in `call_hook'                                                                                                
  lib/redmine/hook.rb:158:in `call_hook'                                                                                               
  app/views/layouts/base.html.erb:75:in `_app_views_layouts_base_html_erb___3045660557403982530_62662640'                              
  app/controllers/wiki_controller.rb:99:in `show'  </pre>

EDIT: 

For some reason migration didn't go?!
I had to manually add column to wiki_pages

**Comment by f0y** [comment]
You have to run migration for plugin. As noted in README

**Comment by majkinetor** [comment]
I did, somehow it didn't do anything, its behaving like its already having that migration installed.. 
I had it  previously installed, then uninstalled, a year ago. 

The new problem is that after hiding/restoring page I am redirected to blank screen where project name is added after the wiki like this.

http://redmine .... /my_project/wiki.my_project

 It looks like something is bad with installation and I can reveret migration or add it the usual way. 

How could I force removal and reinstall again?

**Comment by ghost** [comment]
majkinetor, 
_bundle exec rake redmine:plugins NAME=redmine_private_wiki VERSION=0 RAILS_ENV=production_

But it will not help. :) I also have this issue with redmine 2.3 when redirecting to _wiki.Page_ instead of _wiki/Page_

**Comment by ghost** [comment]
So as I see
_redirect_to project_wiki_path(@project, @page.title)_

need to be changed to

_redirect_to project_wiki_page_path(@project, @page.title)_

at redmine_private_wiki/lib/private_wiki/wiki_controller_patch.rb

**Comment by f0y** [comment]
Can you create a pull request with some tests covering this bug?

On Thu, Apr 18, 2013 at 2:07 PM, Slava Komarov notifications@github.comwrote:

> So as I see
> _redirect_to project_wiki_path(@project https://github.com/project,
> @page.title)_
> 
> need to be changed to
> 
> _redirect_to project_wiki_page_path(@project https://github.com/project,
> @page.title)_
> 
> at redmine_private_wiki/lib/private_wiki/wiki_controller_patch.rb
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/f0y/redmine_private_wiki/issues/20#issuecomment-16568100
> .

## 

Best Wishes,
Oleg Kandaurov

**Comment by ghost** [comment]
Oleg, I would be glad to do it, but I'm a not ruby developer, just a system administrator. So I have a lack of knowledge in it.

**Comment by f0y** [comment]
Ок, fine. Is this a proven solution? In other words, does your solution
work?

On Thu, Apr 18, 2013 at 2:22 PM, Slava Komarov notifications@github.comwrote:

> Oleg, I would be glad to do it, but I'm a not ruby developer, just a
> system administrator. So I have a lack of knowledge in it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/f0y/redmine_private_wiki/issues/20#issuecomment-16568672
> .

## 

Best Wishes,
Oleg Kandaurov

**Comment by ghost** [comment]
Yes, it works fine with renaming to project_wiki_page_path.
I simple grep'ed redmine directory and did not find anything like _project_wiki_path_, but only _project_wiki_page_path_, so I thought that it should work for redmine_private_wiki. :)
Thanks for your plugin. It's useful. Spasibo :)

**Comment by f0y** [comment]
nezachto =)

On Thu, Apr 18, 2013 at 2:28 PM, Slava Komarov notifications@github.comwrote:

> Yes, it works fine with renaming to project_wiki_page_path.
> I simple grep'ed redmine directory and did not find anything like *
> project_wiki_path_, but only *project_wiki_page_path_, so I thought that
> it should work for redmine_private_wiki. :)
> Thanks for your plugin. It's useful. Spasibo :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/f0y/redmine_private_wiki/issues/20#issuecomment-16568917
> .

## 

Best Wishes,
Oleg Kandaurov

**Comment by cforce** [comment]
You are welcome!
