### ISSUE TITLE
Require support for Redmine v2.3

### ISSUE THREAD

**Issue by vineetmantri** [f0y/redmine_private_wiki#27]
Hi,

I am using redmine version 2.3 but your plugins support till version 2.2.
So request you to provide support for 2.3 also.

Thanks
Vineet

**Comment by grooverdan** [comment]
@vineetmantri  I suggest you try it. I just did on 2.4 and it works fine.

**Comment by TravisSpangle** [comment]
Working fine on mine and I'm on 2.5
