### ISSUE TITLE
Amend wiki / code for database

### ISSUE THREAD

**Issue by futurepixels** [f0y/redmine_private_wiki#3]
Not a bug so much, but when I installed the plugin I had to define the development database connection within redmine/config/database.yml which is fine, but if a novice user gets:

```
rake aborted!
Access denied for user 'root'@'localhost' (using password: NO)
```

or anything similar then they may struggle to find the problem.

Would it be better to:

Add these details into the read me
or
Amend the code to ignore the development connect if not defined correctly?

**Comment by f0y** [comment]
I have updated Readme recently, so the issue is resolved
