### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jnv** [f0y/redmine_private_wiki#4]
Hi, I would like to make some modifications to this plugin (e.g. add tests, ensure ChiliProject compatibility) but I am not sure under what conditions I can fork and change this plugin.
Could you please specify copyright conditions and license for this plugin (and add LICENSE file)? Thank you!

**Comment by f0y** [comment]
Hi, This plugin is distributed under MIT license. I will add LICENSE file later.

**Comment by jnv** [comment]
OK, thanks for clearing this up!
