### ISSUE TITLE
compatibility with 1.4.0?

### ISSUE THREAD

**Issue by pramodk** [f0y/redmine_private_wiki#6]
I have installed this plugin with Redmine 1.4.0 and  enabled "manage private wiki pages" in roles and permissions settings. But I am not able to see icon on wiki page to make page private. Can you please check compatibility with above mentioned version? This will be great help.

**Comment by f0y** [comment]
I'll check it ASAP

**Comment by pramodk** [comment]
Thanks. If I manually set private flag in database, functionality works fine. So I think this is issue only with view.

**Comment by f0y** [comment]
I think I have fixed the issue. Could you delete your existing copy of plugin and clone it from the scratch?

**Comment by pramodk** [comment]
Thanks for quick response. Now it works for main wiki page (landing page after clicking wiki tab). But still I can't see icons for other pages. (hide/reveal icon only appears on main wiki page, but doesn't appear for other pages).

**Comment by f0y** [comment]
Btw, what a version of ruby do you use?

**Comment by pramodk** [comment]
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]

and installed gems are:

actionmailer (2.3.14)
actionpack (2.3.14)
activerecord (2.3.14)
activeresource (2.3.14)
activesupport (2.3.14)
bundler (1.1.3)
coderay (1.0.6)
fastercsv (1.5.4)
i18n (0.4.2)
mysql (2.8.1)
net-ldap (0.3.1)
rack (1.1.3)
rails (2.3.14)
rake (0.9.2.2)
rmagick (2.13.1)
ruby-openid (2.1.8)
tzinfo (0.3.33)

**Comment by f0y** [comment]
I cannot reproduce the bug. I have installed redmine 1.4.2 and the plugin and it works me. It is really strange.  The only thing I can suggest is to try it on another web browser and to check that javascript is enabled.

**Comment by pramodk** [comment]
Ok, this  looks like error for my wiki structure. I have one main page i.e. WikiStart and all other are sub-pages under main page. So hide-reveal icon appears now only on main page and not on sub-pages. This javascript fails for sub-pages:$$("div.wiki.wiki-page h1")[0] and hence icons are inserted at other place in DOM.  (there is h2 element for sub-page and not h1)

**Comment by f0y** [comment]
I understand what is the problem. Fix will be soon.

**Comment by f0y** [comment]
Please, check once again.

**Comment by pramodk** [comment]
working perfectly. thanks lot!
